spring.application.name=university-library
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/library_db?schema=public
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# 512 bits secret key neccesary for execution of the project just
# find "generate secret key 512 bits" on google
jwt.secret=4pzk2qtRRVyrJ54gZvynSgsQqapsKn2ViDpiGGz3wd5DYHvyzMIMF4fYEz7QNlqswmL4PYQ1NZH18Ik0KkN3Wp
jwt.expirationn=3600000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
